### ISSUE TITLE
Overview and Decisions: Isolate PDF specific styles

### ISSUE THREAD

**Issue by brittweinstein** [openstax/webview#2277] opened 2019-10-01 21:04 UTC
@helenemccarron commented on [Mon Feb 18 2019](https://github.com/openstax/cnx-recipes/issues/862)

This is tracked in Unified in https://github.com/openstax/unified/issues/168

The work done matches the coding section of https://github.com/openstax/unified/issues/168.
The checkbox in coding should be checked when this is complete.
--- 

Decouple styles that apply only to PDF from styles that may apply to other platforms (specifically, Unified). 

The current structure needs to include support for platform specific styles as well as a global approach to styles that are common across platforms (colors, etc.)

### PDF specific
- [ ] Folio (`@page`)
- [ ] PDF global config: sizing, margin, bleeds
- [ ] Splash Images specific (maybe 2 versions)
- [ ] TOC 
- [ ] Page breaks (https://github.com/openstax/cnx-recipes/issues/442)
- [ ] any PrinceXML specific declarations: footnotes
- [ ] global tweaks to shared components
- [ ] icons

### Global changes:
- [ ] contextualize selectors using page level selector rather than nesting
- [ ] Finalize platform infrastructure. (https://github.com/openstax/cnx-recipes/issues/826)

###  Recipe changes:
-  [x] change `data-type="chapter"` > `.chapter` on the page (https://github.com/openstax/cnx-recipes/issues/915)

### REX specific
- [ ] Responsive design
- [ ] iFrames
- [ ] PrinceXML declaration equivalent in REX (if needed)
- [ ] global tweaks to shared components

---

@brittweinstein commented on [Wed Apr 03 2019](https://github.com/openstax/cnx-recipes/issues/862#issuecomment-479650976)

@helenemccarron please put a points estimate on this when you can.

---

@brittweinstein commented on [Mon May 06 2019](https://github.com/openstax/cnx-recipes/issues/862#issuecomment-489680053)

@helenemccarron please put points on this when you can

---

@brittweinstein commented on [Mon Jun 03 2019](https://github.com/openstax/cnx-recipes/issues/862#issuecomment-498305237)

This will be needed for Baked Styles in REX

**Comment by helenemccarron** [comment] 2019-12-02 16:08
This looks like a duplicate of https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/862 - closing

**Closed by helenemccarron** 2019-12-02 16:08 UTC
Labels: baked.styles
