### ISSUE TITLE
NEWLINE TESTING: Image of Figure 1 in Introduction of Ch 1 is missing in staging

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/webview#2128] opened 2018-12-11 19:10 UTC
Image of Figure 1 in Introduction of Ch 1 is missing in staging.

Staging URL: https://staging.cnx.org/contents/p7ovuIkl@7.1:gMXC1GEM@11/Introduction

Production URL: https://cnx.org/contents/p7ovuIkl@6.16:gMXC1GEM@7/Introduction

Screenshot comparing staging vs. production (safari)

<img width="1675" alt="screen shot 2018-12-11 at 1 08 34 pm" src="https://user-images.githubusercontent.com/40276461/49823783-1bc16f80-fd46-11e8-914b-98ef7861b20b.png">

Screenshot in (chrome)
<img width="1455" alt="screen shot 2018-12-11 at 1 43 57 pm" src="https://user-images.githubusercontent.com/40276461/49825814-ee2af500-fd4a-11e8-8091-7881e33e5327.png">

**Comment by openstaxalina** [comment] 2019-01-29 20:33
duplicate of https://github.com/openstax/cnx-recipes/issues/794; closing.

**Closed by openstaxalina** 2019-01-29 20:33 UTC
