### ISSUE TITLE
math spacing issues with <munder> followed by <mi>

### ISSUE THREAD

**Issue by lwtchu** [openstax/webview#2195] opened 2019-02-20 17:46 UTC
Location: https://cnx.org/contents/i4nRcikn@3.8:eJ08AsuX@4/Continuity

PDF
<img width="792" alt="screen shot 2019-02-20 at 12 13 15 pm" src="https://user-images.githubusercontent.com/11299125/53112161-4842f600-3504-11e9-80b1-b69c811a5d50.png">

Webview:
![screen shot 2019-02-20 at 11 41 59 am](https://user-images.githubusercontent.com/11299125/53112542-11b9ab00-3505-11e9-80b9-b85729e61d2c.png)

Problem: The italic f(x) is running into the lim text.
Ideally it should look like the PDF.

Note: not super urgent as there was only one complaint so far but it does look inconsistent.

**Comment by openstaxalina** [comment] 2019-02-20 19:16
Note:
Similar content also appears in UPhysics, and it is CORRECT there in Web view - with a space between the Lim and the function, plus the stuff underneath. https://cnx.org/contents/1Q9uMg_a@12.5:SXupocJY@7/16-4-Energy-and-Power-of-a-Wave (see about halfway down the page, under Power in Waves, dk=lim 1/2...

Here is a screenshot of the markup; note that there is not a space in the markup.
<img width="370" alt="screen shot 2019-02-20 at 12 08 12 pm" src="https://user-images.githubusercontent.com/7863733/53117974-b0e49f80-3511-11e9-8528-b49753b36dbd.png">

**Comment by openstaxalina** [comment] 2019-02-20 19:17
Note:
Precalc Webview has a similar but not the same issue.  The webview has no spaces (which is definitely wrong), but the pdf is correct with a space after the limits.    https://cnx.org/contents/_VPq4foj@9.4:QTGFrujQ@8/Continuity

<img width="360" alt="screen shot 2019-02-20 at 12 25 05 pm" src="https://user-images.githubusercontent.com/7863733/53118057-df627a80-3511-11e9-93bd-eb21d8e96ddf.png">

**Comment by openstaxalina** [comment] 2019-05-16 00:15
Retested with Calculus baked on katalyst01; this issue seems to still be present.  https://katalyst01.cnx.org/contents/i4nRcikn@4.1:eJ08AsuX@4/2-4-Continuity

**Comment by lwtchu** [comment] 2019-05-21 14:28
Please investigate whether or not the content is marked up correctly in Calculus (in UPhysics, it looks correct).

**Comment by yblock** [comment] 2019-05-21 14:55
The mathML looks the same to me. There isn't a manual space being added in markup. This may be caused by the `<m:munder>` object being against an italicized letter? In other cases the `<m:munder>` object is up against a math object or number.

**Comment by openstaxalina** [comment] 2019-05-21 16:03
ooh @yblock that's a good point.  This may be a bug in MathJax (the math renderer that webview uses, whereas the PDF uses a different renderer).  I'd like to get @philschatz's opinion on this and whether/how we could open a bug with MathJax...I will message Phil.

**Comment by openstaxalina** [comment] 2019-05-21 16:05
Screenshot of display working as intended from UPhysics:
![Screen Shot 2019-05-21 at 11 03 29 AM](https://user-images.githubusercontent.com/7863733/58111987-223af980-7bb8-11e9-967a-98572dcd40af.png)




Screenshot of display **not** working when it's up against an italicized letter:
![screen shot 2019-02-20 at 11 41 59 am](https://user-images.githubusercontent.com/11299125/53112542-11b9ab00-3505-11e9-80b9-b85729e61d2c.png)

**Comment by brittweinstein** [comment] 2019-05-24 14:37
@philschatz please weigh in above.

**Comment by philschatz** [comment] 2019-05-24 15:39
It looks like a configuration problem on our part.

Example of the MathML breaking: https://jsfiddle.net/philschatz/9qzcgaf7/0/
Example of the MathML working: https://jsfiddle.net/philschatz/9qzcgaf7/1/


The only difference between the two is the actual MathJax JavaScript file that is loaded:

- Breaking: `.../2.7.4/MathJax.js?config=...`
- Working: `.../2.7.4/latest.js?config=...`

Once it is changed we will likely need to verify all the math.

**Comment by openstaxalina** [comment] 2019-05-24 17:08
This will be fixed in REX.  I do not think we need to make the same fix in webview, as books will be moving to REX.  Closing.

**Closed by openstaxalina** 2019-05-24 17:08 UTC
Labels: assignable.webview, baked.PDF, book:calculus, book:precalculus, prio:low
