### ISSUE TITLE
Not_converted_yet messages

### ISSUE THREAD

**Issue by wilkus27** [openstax/webview#2124] opened 2018-12-11 14:52 UTC
On katalyst01 (e.g https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:tiLfHQfp@5/9-4-Divided-Government-and-Partisan-Polarization) through the whole book there are messages **Not_converted_yet**:

![not_con_yet](https://user-images.githubusercontent.com/40228854/49808221-51715300-fd5c-11e8-8aa9-656b8fe178e9.JPG)

They are appear in paragraphs with references:

![not_con_yet_pdf](https://user-images.githubusercontent.com/40228854/49808307-89789600-fd5c-11e8-90a0-a0da746f3d28.JPG)

**Comment by openstaxalina** [comment] 2018-12-12 15:54
@Bkblodget could you take a look at this with the team when you get a chance?  This should have been fixed by https://github.com/Connexions/rhaptos.cnxmlutils/pull/166.

I haven't been able to replicate this on staging or production.

**Comment by Bkblodget** [comment] 2018-12-12 18:57
@openstaxalina It seems this issue and https://github.com/Connexions/webview/issues/2100 are the same. It looks like Ross, Helene & Brittany J will be doing to paired programming to fix this - hopefully for 1.15.19 release. 

@brittweinstein do you and Alina think we should combine these issues into one or leave them both open?

**Comment by brittweinstein** [comment] 2018-12-12 19:03
@Bkblodget I think it's ok to have this just in one place--especially since this is a shared repo.

**Comment by openstaxalina** [comment] 2018-12-12 19:21
closing, will be fixed with https://github.com/Connexions/webview/issues/2100

**Comment by openstaxalina** [comment] 2018-12-12 19:24
Actually, I don't think this is the same issue.  This should have been fixed with Connexions/rhaptos.cnxmlutils#166 (and it **was** fixed on staging and production).  

#2100 is a the same issue, but in a different location in a different book.  It was probably never targeted to be fixed with Connexions/rhaptos.cnxmlutils#166.

Therefore, I'd like to keep this open if possible.  The fact that Connexions/rhaptos.cnxmlutils#166 doesn't seem to be working on Katalyst01 will make testing very challenging for Katalyst, since they are seeing all these errors that should have been fixed.

**Comment by marcjeannott** [comment] 2019-01-22 15:18
Verified on Production
![2019-01-22_09-16-53](https://user-images.githubusercontent.com/33228728/51544932-9215bf00-1e26-11e9-96cf-9b8443d99bad.jpg)

**Closed by marcjeannott** 2019-01-22 15:18 UTC
Labels: book:american.government

**Comment by openstaxalina** [comment] 2019-02-13 17:00
Confirmed not seeing this in AmGov2e on production; citations appear properly:
<img width="1322" alt="screen shot 2019-02-13 at 10 59 49 am" src="https://user-images.githubusercontent.com/7863733/52729311-8a0cf300-2f7e-11e9-90dd-e73f3f143923.png">
