### ISSUE TITLE
Bad placement of images in Problems section

### ISSUE THREAD

**Issue by apienk** [openstax/webview#1595] opened 2018-01-31 15:30 UTC
![image](https://user-images.githubusercontent.com/9961826/35631230-a6266c6a-06a3-11e8-84ce-0ac3fb412b7a.png)
When the last line of preceding `<para>` is short image tends to be inserted inline.

Example link: https://cnx.org/contents/1Q9uMg_a@9.1:KZu_UBk-@9.1/Chapter-Review (scroll down to Problems)

**Comment by aiwenar** [comment] 2018-02-06 15:45
I had a look at the generated code, and it's simply a case of `<img>`s begin `display: inline` by default (why, w3c, why?). The simplest fix would be to add the following to book stylesheet

```css
content-selector p > img {
    display: block;
}
```

**Comment by openstaxalina** [comment] 2019-03-12 15:45
![Screen Shot 2019-03-12 at 10 42 12 AM](https://user-images.githubusercontent.com/7863733/54214222-d1ba6800-44b3-11e9-9eaa-d5417a03e080.png)
https://cnx.org/contents/1Q9uMg_a@12.5:KZu_UBk-@12.5/Chapter-Review
Cannot reproduce; closing this issue.

**Closed by openstaxalina** 2019-03-12 15:45 UTC
